window.FILES_DATA = [
  {
    "name": "L1_Manual_Counts_S0__Discussion.html",
    "title": "Hemocytometer",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S0__Discussion.html",
    "size": 331404,
    "sizeFormatted": "323.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790453765.8816311
  },
  {
    "name": "L1_Manual_Counts_S1_Hemocytometer.pdf",
    "title": "Hemocytometer",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S1_Hemocytometer.pdf",
    "size": 851661,
    "sizeFormatted": "831.7 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922744.7424567
  },
  {
    "name": "L1_Manual_Counts_S2_Hematocrit.pdf",
    "title": "Hematocrit",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S2_Hematocrit.pdf",
    "size": 517492,
    "sizeFormatted": "505.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922761.2596922
  },
  {
    "name": "L1_Manual_Counts_S3_Mind_Map.html",
    "title": "Manual Counts",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S3_Mind_Map.html",
    "size": 100467,
    "sizeFormatted": "98.1 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790537673.117753
  },
  {
    "name": "L2_Slide_Preparation_S0_Discussion.html",
    "title": "Slide Prep",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S0_Discussion.html",
    "size": 260221,
    "sizeFormatted": "254.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790453765.9582088
  },
  {
    "name": "L2_Slide_Preparation_S1_PBS_Preparation.pdf",
    "title": "PBS Preparation",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S1_PBS_Preparation.pdf",
    "size": 1976752,
    "sizeFormatted": "1.9 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922775.2107549
  },
  {
    "name": "L2_Slide_Preparation_S2_Mind_Map.html",
    "title": "Slide Preparation",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S2_Mind_Map.html",
    "size": 105790,
    "sizeFormatted": "103.3 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790537673.1228125
  },
  {
    "name": "L3_Slide_Evaluation_S0_Discussion.html",
    "title": "Slide Eval",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S0_Discussion.html",
    "size": 407463,
    "sizeFormatted": "397.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790453766.0510025
  },
  {
    "name": "L3_Slide_Evaluation_S1_PBS_Evaluation.pdf",
    "title": "PBS Evaluation",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S1_PBS_Evaluation.pdf",
    "size": 1673183,
    "sizeFormatted": "1.6 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786992156.0
  },
  {
    "name": "L3_Slide_Evaluation_S2_PBS_Morphologies.pdf",
    "title": "PBS Morphologies",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S2_PBS_Morphologies.pdf",
    "size": 1499745,
    "sizeFormatted": "1.4 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786992172.0
  },
  {
    "name": "L3_Slide_Evaluation_S3_Mind_Map.html",
    "title": "Slide Evaluation",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S3_Mind_Map.html",
    "size": 93820,
    "sizeFormatted": "91.6 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790537673.1288729
  },
  {
    "name": "L4_CBC_Analysis_S0_Discussion.html",
    "title": "CBC Analysis",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S0_Discussion.html",
    "size": 268189,
    "sizeFormatted": "261.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790453766.130587
  },
  {
    "name": "L4_CBC_Analysis_S1_Principles.pdf",
    "title": "Principles",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S1_Principles.pdf",
    "size": 1167754,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1787237822.0
  },
  {
    "name": "L4_CBC_Analysis_S2_Parameters.pdf",
    "title": "Parameters",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S2_Parameters.pdf",
    "size": 1278033,
    "sizeFormatted": "1.2 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1787268744.3925018
  },
  {
    "name": "L4_CBC_Analysis_S3_Mind_Map.html",
    "title": "CBC Analysis",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S3_Mind_Map.html",
    "size": 113071,
    "sizeFormatted": "110.4 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790537673.1335077
  },
  {
    "name": "L5_Microcytic_S0_Discussion.html",
    "title": "Microcytic Anemias",
    "path": "Laboratory/Erythrocytes/L5_Microcytic_S0_Discussion.html",
    "size": 322179,
    "sizeFormatted": "314.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790453686.9933333
  },
  {
    "name": "L5_Microcytic_S1_Mind_Map.html",
    "title": "Microcytic",
    "path": "Laboratory/Erythrocytes/L5_Microcytic_S1_Mind_Map.html",
    "size": 110661,
    "sizeFormatted": "108.1 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790537673.1386247
  },
  {
    "name": "L6_Hemoglobinopathy_S0_Discussion.html",
    "title": "Hemoglobinopathy",
    "path": "Laboratory/Erythrocytes/L6_Hemoglobinopathy_S0_Discussion.html",
    "size": 326421,
    "sizeFormatted": "318.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790453687.04976
  },
  {
    "name": "L6_Hemoglobinopathy_S1_Mind_Map.html",
    "title": "Hemoglobinopathy & Thalassemia",
    "path": "Laboratory/Erythrocytes/L6_Hemoglobinopathy_S1_Mind_Map.html",
    "size": 125097,
    "sizeFormatted": "122.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790537673.1432214
  },
  {
    "name": "L7_Macrocytic_S0_Discussion.html",
    "title": "Macrocytic",
    "path": "Laboratory/Erythrocytes/L7_Macrocytic_S0_Discussion.html",
    "size": 309474,
    "sizeFormatted": "302.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790453687.0883548
  },
  {
    "name": "L7_Macrocytic_S1_Mind_Map.html",
    "title": "Macrocytic",
    "path": "Laboratory/Erythrocytes/L7_Macrocytic_S1_Mind_Map.html",
    "size": 120327,
    "sizeFormatted": "117.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790537673.148379
  },
  {
    "name": "L8_Normocytic_S0_Discussion.html",
    "title": "Normocytic",
    "path": "Laboratory/Erythrocytes/L8_Normocytic_S0_Discussion.html",
    "size": 340105,
    "sizeFormatted": "332.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790453686.7760832
  },
  {
    "name": "L8_Normocytic_S1_Mind_Map.html",
    "title": "Normocytic",
    "path": "Laboratory/Erythrocytes/L8_Normocytic_S1_Mind_Map.html",
    "size": 135043,
    "sizeFormatted": "131.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790537673.15369
  },
  {
    "name": "L10_AML_S0_Discussion.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L10_AML_S0_Discussion.html",
    "size": 311630,
    "sizeFormatted": "304.3 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790525299.5396144
  },
  {
    "name": "L10_AML_S1_Mind_Map.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L10_AML_S1_Mind_Map.html",
    "size": 90283,
    "sizeFormatted": "88.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790537673.1639042
  },
  {
    "name": "L11_MPN_MDS_S0_Discussion.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L11_MPN_MDS_S0_Discussion.html",
    "size": 306407,
    "sizeFormatted": "299.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790525310.699811
  },
  {
    "name": "L11_MPN_MDS_S1_Mind_Map.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L11_MPN_MDS_S1_Mind_Map.html",
    "size": 115567,
    "sizeFormatted": "112.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790537673.16843
  },
  {
    "name": "L12_LACLN_S0_Discussion.html",
    "title": "Lymphoid Neoplasms",
    "path": "Laboratory/Leukocytes/L12_LACLN_S0_Discussion.html",
    "size": 309806,
    "sizeFormatted": "302.5 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790525322.6249294
  },
  {
    "name": "L12_LACLN_S1_Mind_Map.html",
    "title": "Lymphoid Neoplasms",
    "path": "Laboratory/Leukocytes/L12_LACLN_S1_Mind_Map.html",
    "size": 127432,
    "sizeFormatted": "124.4 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790537673.172889
  },
  {
    "name": "L13_BM_Flow_S0_Discussion.html",
    "title": "Bone Marrow & Flow Cytometry",
    "path": "Laboratory/Leukocytes/L13_BM_Flow_S0_Discussion.html",
    "size": 333154,
    "sizeFormatted": "325.3 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790454973.8145554
  },
  {
    "name": "L13_BM_Flow_S1_Mind_Map.html",
    "title": "Bone Marrow & Flow Cytometry",
    "path": "Laboratory/Leukocytes/L13_BM_Flow_S1_Mind_Map.html",
    "size": 138640,
    "sizeFormatted": "135.4 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790537673.1774096
  },
  {
    "name": "L9_Benign_S0_Discussion.html",
    "title": "Benign Disorders",
    "path": "Laboratory/Leukocytes/L9_Benign_S0_Discussion.html",
    "size": 342746,
    "sizeFormatted": "334.7 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790525285.274667
  },
  {
    "name": "L9_Benign_S1_Mind_Map.html",
    "title": "Benign Disorders",
    "path": "Laboratory/Leukocytes/L9_Benign_S1_Mind_Map.html",
    "size": 128473,
    "sizeFormatted": "125.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790537673.1587265
  },
  {
    "name": "L5_Iron_Heme_S0_Discussion.html",
    "title": "Iron Heme",
    "path": "Lecture/Erythrocytes/L5_Iron_Heme_S0_Discussion.html",
    "size": 370938,
    "sizeFormatted": "362.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790453686.4636707
  },
  {
    "name": "L5_Iron_Heme_S1_Mind_Map.html",
    "title": "Iron & Heme",
    "path": "Lecture/Erythrocytes/L5_Iron_Heme_S1_Mind_Map.html",
    "size": 146708,
    "sizeFormatted": "143.3 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790537673.056891
  },
  {
    "name": "L6_Hemoglobinopathy_S0_Discussion.html",
    "title": "Hemoglobinopathies",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S0_Discussion.html",
    "size": 381915,
    "sizeFormatted": "373.0 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790453686.597993
  },
  {
    "name": "L6_Hemoglobinopathy_S1_Mind_Map.html",
    "title": "Hemoglobinopathy",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S1_Mind_Map.html",
    "size": 131225,
    "sizeFormatted": "128.1 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790537673.0629191
  },
  {
    "name": "L6_Hemoglobinopathy_S2_Flow_Chart_Qualitative.pdf",
    "title": "Qualitative",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S2_Flow_Chart_Qualitative.pdf",
    "size": 307987,
    "sizeFormatted": "300.8 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649301.0
  },
  {
    "name": "L6_Hemoglobinopathy_S3_Flow_Chart_Quantitative.pdf",
    "title": "Quantitative",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S3_Flow_Chart_Quantitative.pdf",
    "size": 311224,
    "sizeFormatted": "303.9 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649304.0
  },
  {
    "name": "L6_Hemoglobinopathy_S4_Flow_Chart_All.pdf",
    "title": "All",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S4_Flow_Chart_All.pdf",
    "size": 319691,
    "sizeFormatted": "312.2 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649298.0
  },
  {
    "name": "L7_Macros_Hypos_S0_Discussion.html",
    "title": "Macros Hypos",
    "path": "Lecture/Erythrocytes/L7_Macros_Hypos_S0_Discussion.html",
    "size": 347060,
    "sizeFormatted": "338.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790453686.651954
  },
  {
    "name": "L7_Macros_Hypos_S4_Mind_Map.html",
    "title": "Macrocytic & Hypoproliferative",
    "path": "Lecture/Erythrocytes/L7_Macros_Hypos_S4_Mind_Map.html",
    "size": 129985,
    "sizeFormatted": "126.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790537673.0689511
  },
  {
    "name": "L8_Hemolytic_S0_Discussion.html",
    "title": "Hemolytic",
    "path": "Lecture/Erythrocytes/L8_Hemolytic_S0_Discussion.html",
    "size": 456642,
    "sizeFormatted": "445.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790453686.7304275
  },
  {
    "name": "L8_Hemolytic_S1_Mind_Map.html",
    "title": "Hemolytic",
    "path": "Lecture/Erythrocytes/L8_Hemolytic_S1_Mind_Map.html",
    "size": 147900,
    "sizeFormatted": "144.4 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790537673.0750458
  },
  {
    "name": "L10_AML_S0_Discussion.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L10_AML_S0_Discussion.html",
    "size": 330733,
    "sizeFormatted": "323.0 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1790461333.844735
  },
  {
    "name": "L10_AML_S1_Mind_Map.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L10_AML_S1_Mind_Map.html",
    "size": 130379,
    "sizeFormatted": "127.3 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790537673.086725
  },
  {
    "name": "L11_MPN_MDS_S0_Discussion.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L11_MPN_MDS_S0_Discussion.html",
    "size": 348550,
    "sizeFormatted": "340.4 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1790461348.3791604
  },
  {
    "name": "L11_MPN_MDS_S1_Mind_Map.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L11_MPN_MDS_S1_Mind_Map.html",
    "size": 134145,
    "sizeFormatted": "131.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790537673.0927696
  },
  {
    "name": "L12_ALL_S0_Discussion.html",
    "title": "Lymphoid Neoplasms",
    "path": "Lecture/Leukocytes/L12_ALL_S0_Discussion.html",
    "size": 325872,
    "sizeFormatted": "318.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1790469124.7583191
  },
  {
    "name": "L12_ALL_S1_Mind_Map.html",
    "title": "Lymphoid Neoplasms",
    "path": "Lecture/Leukocytes/L12_ALL_S1_Mind_Map.html",
    "size": 126304,
    "sizeFormatted": "123.3 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790537673.097291
  },
  {
    "name": "L13_BM_Flow_S0_Discussion.html",
    "title": "Bone Marrow & Flow Cytometry",
    "path": "Lecture/Leukocytes/L13_BM_Flow_S0_Discussion.html",
    "size": 335233,
    "sizeFormatted": "327.4 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1790461381.9198096
  },
  {
    "name": "L13_BM_Flow_S1_Mind_Map.html",
    "title": "Bone Marrow & Flow Cytometry",
    "path": "Lecture/Leukocytes/L13_BM_Flow_S1_Mind_Map.html",
    "size": 137707,
    "sizeFormatted": "134.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790537673.1043098
  },
  {
    "name": "L9_Benign_S0_Discussion.html",
    "title": "Benign Disorders",
    "path": "Lecture/Leukocytes/L9_Benign_S0_Discussion.html",
    "size": 417827,
    "sizeFormatted": "408.0 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1790461319.894788
  },
  {
    "name": "L9_Benign_S1_Mind_Map.html",
    "title": "Benign Disorders",
    "path": "Lecture/Leukocytes/L9_Benign_S1_Mind_Map.html",
    "size": 120828,
    "sizeFormatted": "118.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790537673.0810971
  },
  {
    "name": "L1_Hematopoiesis_S0_Discussion.html",
    "title": "Hematopoiesis",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S0_Discussion.html",
    "size": 365888,
    "sizeFormatted": "357.3 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1790453765.462487
  },
  {
    "name": "L1_Hematopoiesis_S1_Blood_Composition.pdf",
    "title": "Blood Composition",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S1_Blood_Composition.pdf",
    "size": 317849,
    "sizeFormatted": "310.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019666.0
  },
  {
    "name": "L1_Hematopoiesis_S2_Hematopoiesis_Sites.pdf",
    "title": "Hematopoiesis Sites",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S2_Hematopoiesis_Sites.pdf",
    "size": 1318259,
    "sizeFormatted": "1.3 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019744.0
  },
  {
    "name": "L1_Hematopoiesis_S3_Hematopoiesis_Process.pdf",
    "title": "Hematopoiesis Process",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S3_Hematopoiesis_Process.pdf",
    "size": 1111963,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019852.0
  },
  {
    "name": "L1_Hematopoiesis_S4_Mind_Map.html",
    "title": "Hematopoiesis",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S4_Mind_Map.html",
    "size": 113523,
    "sizeFormatted": "110.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790537673.037544
  },
  {
    "name": "L2_BCE_RBC-HGB_S0_Discussion.html",
    "title": "BCE RBC",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S0_Discussion.html",
    "size": 313443,
    "sizeFormatted": "306.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1790453765.5740986
  },
  {
    "name": "L2_BCE_RBC-HGB_S1_Erythrocyte.pdf",
    "title": "Erythrocyte",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S1_Erythrocyte.pdf",
    "size": 1418003,
    "sizeFormatted": "1.4 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786114769.0
  },
  {
    "name": "L2_BCE_RBC-HGB_S2_Hemoglobin.pdf",
    "title": "Hemoglobin",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S2_Hemoglobin.pdf",
    "size": 840386,
    "sizeFormatted": "820.7 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786114815.0
  },
  {
    "name": "L2_BCE_RBC-HGB_S3_Mind_Map.html",
    "title": "Erythrocytes & Hemoglobin",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S3_Mind_Map.html",
    "size": 99490,
    "sizeFormatted": "97.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790537673.0423672
  },
  {
    "name": "L3_BCE_WBC-PLT_S0_Discussion.html",
    "title": "BCE WBC",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S0_Discussion.html",
    "size": 328834,
    "sizeFormatted": "321.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1790453765.7202551
  },
  {
    "name": "L3_BCE_WBC-PLT_S1_Granulocytes.pdf",
    "title": "Granulocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S1_Granulocytes.pdf",
    "size": 534379,
    "sizeFormatted": "521.9 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538835.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S2_Lymphocytes.pdf",
    "title": "Lymphocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S2_Lymphocytes.pdf",
    "size": 458102,
    "sizeFormatted": "447.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538871.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S3_Monocytes-Platelets.pdf",
    "title": "Monocytes & Platelets",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S3_Monocytes-Platelets.pdf",
    "size": 351447,
    "sizeFormatted": "343.2 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538884.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S4_Mind_Map.html",
    "title": "Leukocytes & Platelets",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S4_Mind_Map.html",
    "size": 94180,
    "sizeFormatted": "92.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790537673.0463576
  },
  {
    "name": "L4_RBC_Analysis_S0_Discussion.html",
    "title": "CBC",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S0_Discussion.html",
    "size": 259956,
    "sizeFormatted": "253.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1790453765.7948189
  },
  {
    "name": "L4_RBC_Analysis_S1_RBC_Indices.pdf",
    "title": "RBC Indices",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S1_RBC_Indices.pdf",
    "size": 683427,
    "sizeFormatted": "667.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539106.0
  },
  {
    "name": "L4_RBC_Analysis_S2_RBC_Poikilocytes.pdf",
    "title": "RBC Poikilocytes",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S2_RBC_Poikilocytes.pdf",
    "size": 1156067,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539118.0
  },
  {
    "name": "L4_RBC_Analysis_S3_RBC_Inclusions.pdf",
    "title": "RBC Inclusions",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S3_RBC_Inclusions.pdf",
    "size": 1048420,
    "sizeFormatted": "1023.8 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539130.0
  },
  {
    "name": "L4_RBC_Analysis_S4_Mind_Map.html",
    "title": "RBC Analysis",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S4_Mind_Map.html",
    "size": 96207,
    "sizeFormatted": "94.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790537673.0518913
  },
  {
    "name": "L1_Hematopoiesis_S1_Blood_Composition_Video",
    "title": "Blood Composition",
    "path": "https://youtu.be/jG0gyuxHCss",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/jG0gyuxHCss",
    "mtime": 0
  },
  {
    "name": "L1_Hematopoiesis_S2_Hematopoiesis_Sites_Video",
    "title": "Hematopoiesis Sites",
    "path": "https://youtu.be/-tAUTqSBBV8",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/-tAUTqSBBV8",
    "mtime": 0
  },
  {
    "name": "L1_Hematopoiesis_S3_Hematopoiesis_Process_Video",
    "title": "Hematopoiesis Process",
    "path": "https://youtu.be/F6M8pZDxGdw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/F6M8pZDxGdw",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_Hemocytometer_Video",
    "title": "Hemocytometer",
    "path": "https://youtu.be/GEtNXeqoKlo",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/GEtNXeqoKlo",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Demo_Hemocytometer_Thrombo_TIC_Setup",
    "title": "Hemocytometer Thrombo-TIC Setup",
    "path": "https://youtu.be/QTzEcoxlkoI",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/QTzEcoxlkoI",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_2_Demo_Hemocytometer_Charging",
    "title": "Hemocytometer Charging",
    "path": "https://youtu.be/m-EP2Vj_CQo",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/m-EP2Vj_CQo",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_3_Demo_Hemocytometer_Read",
    "title": "Hemocytometer Read",
    "path": "https://youtu.be/IdD9H5buUrA",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/IdD9H5buUrA",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Tool_Week_2_Hemocytometer",
    "title": "Week 2 Hemocytometer",
    "path": "https://teach.brettmrice.com/#week-2",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://teach.brettmrice.com/#week-2",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_Hematocrit_Video",
    "title": "Hematocrit",
    "path": "https://youtu.be/lojI06C6A5Q",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/lojI06C6A5Q",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_1_Demo_Hematocrit_Setup",
    "title": "Hematocrit Setup",
    "path": "https://youtu.be/4W0XvRYXTJw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/4W0XvRYXTJw",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_2_Demo_Hematocrit_Centrifuge_Read",
    "title": "Hematocrit Centrifuge & Read",
    "path": "https://youtu.be/0_Id8VUFsQ4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/0_Id8VUFsQ4",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Trainer_Hematocrit_Reader",
    "title": "Hematocrit Reader",
    "path": "https://www.brettmrice.com/Hematocrit-Trainer/",
    "size": 0,
    "sizeFormatted": "Interactive Trainer",
    "extension": "url",
    "type": "Trainer",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://www.brettmrice.com/Hematocrit-Trainer/",
    "mtime": 0
  },
  {
    "name": "L2_BCE_RBC-HGB_S1_Erythrocyte_Video",
    "title": "Erythrocyte",
    "path": "https://youtu.be/LcgQgGLCt5I",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/LcgQgGLCt5I",
    "mtime": 0
  },
  {
    "name": "L2_BCE_RBC-HGB_S2_Hemoglobin_Video",
    "title": "Hemoglobin",
    "path": "https://youtu.be/Bn2MnwjD51w",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/Bn2MnwjD51w",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_PBS_Preparation_Video",
    "title": "PBS Preparation",
    "path": "https://youtu.be/Mn4t2B3R_UY",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/Mn4t2B3R_UY",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_1_Demo_Slide_Prep_Microcapillary_Tube",
    "title": "Slide Prep Microcapillary Tube",
    "path": "https://youtu.be/_J5hAGrS650",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/_J5hAGrS650",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_2_Demo_Slide_Prep_Applicator_Stick",
    "title": "Slide Prep Applicator Stick",
    "path": "https://youtu.be/cjWf9c6Uqdw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/cjWf9c6Uqdw",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S1_Granulocytes_Video",
    "title": "Granulocytes",
    "path": "https://youtu.be/h-lqd3K_byM",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/h-lqd3K_byM",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S2_Lymphocytes_Video",
    "title": "Lymphocytes",
    "path": "https://youtu.be/dQ7j6_6IZig",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/dQ7j6_6IZig",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S3_Monocytes-Platelets_Video",
    "title": "Monocytes & Platelets",
    "path": "https://youtu.be/S5z8BRAl9f4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/S5z8BRAl9f4",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S1_PBS_Evaluation_Video",
    "title": "PBS Evaluation",
    "path": "https://youtu.be/_RkPRVrStLM",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/_RkPRVrStLM",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_PBS_Morphologies_Video",
    "title": "PBS Morphologies",
    "path": "https://youtu.be/8Q7muZftcao",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/8Q7muZftcao",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_1_Demo_CPS_Tutorial",
    "title": "CPS Tutorial",
    "path": "https://www.youtube.com/watch?v=0m0JuzliCN4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://www.youtube.com/watch?v=0m0JuzliCN4",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_1_Tool_Week_3_Slides",
    "title": "Week 3 Slides",
    "path": "https://teach.brettmrice.com/#week-3",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://teach.brettmrice.com/#week-3",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_2_Tool_Blood_Cell_ID",
    "title": "Blood Cell ID",
    "path": "https://bloodcellid.com/",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://bloodcellid.com/",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S1_RBC_Indices_Video",
    "title": "RBC Indices",
    "path": "https://youtu.be/12lDKTSlcg0",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/12lDKTSlcg0",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S2_RBC_Poikilocytes_Video",
    "title": "RBC Poikilocytes",
    "path": "https://youtu.be/3-FpS1rfeuA",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/3-FpS1rfeuA",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S3_RBC_Inclusions_Video",
    "title": "RBC Inclusions",
    "path": "https://youtu.be/6JfUtpf2mvc",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/6JfUtpf2mvc",
    "mtime": 0
  },
  {
    "name": "L4_CBC_Analysis_S1_Principles_Video",
    "title": "Principles",
    "path": "https://youtu.be/UIS-zmZTZeU",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/UIS-zmZTZeU",
    "mtime": 0
  },
  {
    "name": "L4_CBC_Analysis_S2_Parameters_Video",
    "title": "Parameters",
    "path": "https://youtu.be/113lBFF1Iuw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/113lBFF1Iuw",
    "mtime": 0
  }
];
