window.FILES_DATA = [
  {
    "name": "L1_Manual_Counts_S0__Discussion.html",
    "title": "Hemocytometer",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S0__Discussion.html",
    "size": 364716,
    "sizeFormatted": "356.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1791413530.348865
  },
  {
    "name": "L1_Manual_Counts_S1_Hemocytometer.pdf",
    "title": "Hemocytometer",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S1_Hemocytometer.pdf",
    "size": 851661,
    "sizeFormatted": "831.7 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922744.0
  },
  {
    "name": "L1_Manual_Counts_S2_Hematocrit.pdf",
    "title": "Hematocrit",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S2_Hematocrit.pdf",
    "size": 517492,
    "sizeFormatted": "505.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922761.0
  },
  {
    "name": "L1_Manual_Counts_S3_Mind_Map.html",
    "title": "Manual Counts",
    "path": "Laboratory/CBC_PBS/L1_Manual_Counts_S3_Mind_Map.html",
    "size": 101061,
    "sizeFormatted": "98.7 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790713507.0
  },
  {
    "name": "L2_Slide_Preparation_S0_Discussion.html",
    "title": "Slide Prep",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S0_Discussion.html",
    "size": 293476,
    "sizeFormatted": "286.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1791413530.3793447
  },
  {
    "name": "L2_Slide_Preparation_S1_PBS_Preparation.pdf",
    "title": "PBS Preparation",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S1_PBS_Preparation.pdf",
    "size": 1976752,
    "sizeFormatted": "1.9 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786922775.0
  },
  {
    "name": "L2_Slide_Preparation_S2_Mind_Map.html",
    "title": "Slide Preparation",
    "path": "Laboratory/CBC_PBS/L2_Slide_Preparation_S2_Mind_Map.html",
    "size": 106384,
    "sizeFormatted": "103.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790713244.0
  },
  {
    "name": "L3_Slide_Evaluation_S0_Discussion.html",
    "title": "Slide Eval",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S0_Discussion.html",
    "size": 439618,
    "sizeFormatted": "429.3 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1791413530.4532464
  },
  {
    "name": "L3_Slide_Evaluation_S1_PBS_Evaluation.pdf",
    "title": "PBS Evaluation",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S1_PBS_Evaluation.pdf",
    "size": 1673183,
    "sizeFormatted": "1.6 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786992156.0
  },
  {
    "name": "L3_Slide_Evaluation_S2_PBS_Morphologies.pdf",
    "title": "PBS Morphologies",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S2_PBS_Morphologies.pdf",
    "size": 1499745,
    "sizeFormatted": "1.4 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1786992172.0
  },
  {
    "name": "L3_Slide_Evaluation_S3_Mind_Map.html",
    "title": "Slide Evaluation",
    "path": "Laboratory/CBC_PBS/L3_Slide_Evaluation_S3_Mind_Map.html",
    "size": 94414,
    "sizeFormatted": "92.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790713494.0
  },
  {
    "name": "L4_CBC_Analysis_S0_Discussion.html",
    "title": "CBC Analysis",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S0_Discussion.html",
    "size": 301720,
    "sizeFormatted": "294.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1791413530.4897401
  },
  {
    "name": "L4_CBC_Analysis_S1_Principles.pdf",
    "title": "Principles",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S1_Principles.pdf",
    "size": 1167754,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1787237822.0
  },
  {
    "name": "L4_CBC_Analysis_S2_Parameters.pdf",
    "title": "Parameters",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S2_Parameters.pdf",
    "size": 1278033,
    "sizeFormatted": "1.2 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1787268744.0
  },
  {
    "name": "L4_CBC_Analysis_S3_Mind_Map.html",
    "title": "CBC Analysis",
    "path": "Laboratory/CBC_PBS/L4_CBC_Analysis_S3_Mind_Map.html",
    "size": 113665,
    "sizeFormatted": "111.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / CBC_PBS",
    "mtime": 1790452709.0
  },
  {
    "name": "L5_Microcytic_S0_Discussion.html",
    "title": "Microcytic",
    "path": "Laboratory/Erythrocytes/L5_Microcytic_S0_Discussion.html",
    "size": 355141,
    "sizeFormatted": "346.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1791413530.548201
  },
  {
    "name": "L5_Microcytic_S1_Mind_Map.html",
    "title": "Microcytic",
    "path": "Laboratory/Erythrocytes/L5_Microcytic_S1_Mind_Map.html",
    "size": 111255,
    "sizeFormatted": "108.6 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790713529.0
  },
  {
    "name": "L6_Hemoglobinopathy_S0_Discussion.html",
    "title": "Hemoglobinopathy",
    "path": "Laboratory/Erythrocytes/L6_Hemoglobinopathy_S0_Discussion.html",
    "size": 360361,
    "sizeFormatted": "351.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1791413530.6135867
  },
  {
    "name": "L6_Hemoglobinopathy_S1_Mind_Map.html",
    "title": "Hemoglobinopathy",
    "path": "Laboratory/Erythrocytes/L6_Hemoglobinopathy_S1_Mind_Map.html",
    "size": 125649,
    "sizeFormatted": "122.7 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790713543.0
  },
  {
    "name": "L7_Macrocytic_S0_Discussion.html",
    "title": "Macrocytic &amp; Hypoproliferative",
    "path": "Laboratory/Erythrocytes/L7_Macrocytic_S0_Discussion.html",
    "size": 341764,
    "sizeFormatted": "333.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1791413530.6591487
  },
  {
    "name": "L7_Macrocytic_S1_Mind_Map.html",
    "title": "Macrocytic & Hypoproliferative",
    "path": "Laboratory/Erythrocytes/L7_Macrocytic_S1_Mind_Map.html",
    "size": 120981,
    "sizeFormatted": "118.1 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790713576.0
  },
  {
    "name": "L8_Normocytic_S0_Discussion.html",
    "title": "Normocytic",
    "path": "Laboratory/Erythrocytes/L8_Normocytic_S0_Discussion.html",
    "size": 372484,
    "sizeFormatted": "363.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1791413530.7115378
  },
  {
    "name": "L8_Normocytic_S1_Mind_Map.html",
    "title": "Normocytic",
    "path": "Laboratory/Erythrocytes/L8_Normocytic_S1_Mind_Map.html",
    "size": 135637,
    "sizeFormatted": "132.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Erythrocytes",
    "mtime": 1790713588.0
  },
  {
    "name": "L10_AML_S0_Discussion.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L10_AML_S0_Discussion.html",
    "size": 333899,
    "sizeFormatted": "326.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791413530.1390834
  },
  {
    "name": "L10_AML_S1_Mind_Map.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L10_AML_S1_Mind_Map.html",
    "size": 125175,
    "sizeFormatted": "122.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790975735.8750365
  },
  {
    "name": "L11_MPN_MDS_S0_Discussion.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L11_MPN_MDS_S0_Discussion.html",
    "size": 328347,
    "sizeFormatted": "320.7 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791413530.1838048
  },
  {
    "name": "L11_MPN_MDS_S1_Mind_Map.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Laboratory/Leukocytes/L11_MPN_MDS_S1_Mind_Map.html",
    "size": 127581,
    "sizeFormatted": "124.6 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790975745.7903006
  },
  {
    "name": "L12_LACLN_S0_Discussion.html",
    "title": "Lymphoid Neoplasms",
    "path": "Laboratory/Leukocytes/L12_LACLN_S0_Discussion.html",
    "size": 391907,
    "sizeFormatted": "382.7 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791413530.2401848
  },
  {
    "name": "L12_LACLN_S1_Mind_Map.html",
    "title": "Lymphoid Neoplasms",
    "path": "Laboratory/Leukocytes/L12_LACLN_S1_Mind_Map.html",
    "size": 142434,
    "sizeFormatted": "139.1 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790975754.4351206
  },
  {
    "name": "L13_BM_Flow_S0_Discussion.html",
    "title": "Bone Marrow &amp; Flow Cytometry",
    "path": "Laboratory/Leukocytes/L13_BM_Flow_S0_Discussion.html",
    "size": 377452,
    "sizeFormatted": "368.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791413530.2946048
  },
  {
    "name": "L13_BM_Flow_S1_Mind_Map.html",
    "title": "Bone Marrow & Flow Cytometry",
    "path": "Laboratory/Leukocytes/L13_BM_Flow_S1_Mind_Map.html",
    "size": 138277,
    "sizeFormatted": "135.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791046986.7288303
  },
  {
    "name": "L9_Benign_S0_Discussion.html",
    "title": "Benign Disorders",
    "path": "Laboratory/Leukocytes/L9_Benign_S0_Discussion.html",
    "size": 352025,
    "sizeFormatted": "343.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Laboratory / Leukocytes",
    "mtime": 1791413530.0938528
  },
  {
    "name": "L9_Benign_S1_Mind_Map.html",
    "title": "Benign Disorders",
    "path": "Laboratory/Leukocytes/L9_Benign_S1_Mind_Map.html",
    "size": 130970,
    "sizeFormatted": "127.9 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Laboratory / Leukocytes",
    "mtime": 1790975718.382233
  },
  {
    "name": "L5_Iron_Heme_S0_Discussion.html",
    "title": "Iron &amp; Heme",
    "path": "Lecture/Erythrocytes/L5_Iron_Heme_S0_Discussion.html",
    "size": 404350,
    "sizeFormatted": "394.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1791413529.7494545
  },
  {
    "name": "L5_Iron_Heme_S1_Mind_Map.html",
    "title": "Iron & Heme",
    "path": "Lecture/Erythrocytes/L5_Iron_Heme_S1_Mind_Map.html",
    "size": 147302,
    "sizeFormatted": "143.8 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790713941.0
  },
  {
    "name": "L6_Hemoglobinopathy_S0_Discussion.html",
    "title": "Hemoglobinopathy",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S0_Discussion.html",
    "size": 415803,
    "sizeFormatted": "406.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1791413529.896207
  },
  {
    "name": "L6_Hemoglobinopathy_S1_Mind_Map.html",
    "title": "Hemoglobinopathy",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S1_Mind_Map.html",
    "size": 131819,
    "sizeFormatted": "128.7 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790713941.0
  },
  {
    "name": "L6_Hemoglobinopathy_S2_Flow_Chart_Qualitative.pdf",
    "title": "Qualitative",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S2_Flow_Chart_Qualitative.pdf",
    "size": 307987,
    "sizeFormatted": "300.8 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649301.0
  },
  {
    "name": "L6_Hemoglobinopathy_S3_Flow_Chart_Quantitative.pdf",
    "title": "Quantitative",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S3_Flow_Chart_Quantitative.pdf",
    "size": 311224,
    "sizeFormatted": "303.9 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649304.0
  },
  {
    "name": "L6_Hemoglobinopathy_S4_Flow_Chart_All.pdf",
    "title": "All",
    "path": "Lecture/Erythrocytes/L6_Hemoglobinopathy_S4_Flow_Chart_All.pdf",
    "size": 319691,
    "sizeFormatted": "312.2 KB",
    "extension": "pdf",
    "type": "Flow Chart",
    "category": "Lecture / Erythrocytes",
    "mtime": 1789649298.0
  },
  {
    "name": "L7_Macros_Hypos_S0_Discussion.html",
    "title": "Macrocytic &amp; Hypoproliferative",
    "path": "Lecture/Erythrocytes/L7_Macros_Hypos_S0_Discussion.html",
    "size": 380705,
    "sizeFormatted": "371.8 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1791413529.9576893
  },
  {
    "name": "L7_Macros_Hypos_S4_Mind_Map.html",
    "title": "Macrocytic & Hypoproliferative",
    "path": "Lecture/Erythrocytes/L7_Macros_Hypos_S4_Mind_Map.html",
    "size": 130579,
    "sizeFormatted": "127.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790713941.0
  },
  {
    "name": "L8_Hemolytic_S0_Discussion.html",
    "title": "Hemolytic",
    "path": "Lecture/Erythrocytes/L8_Hemolytic_S0_Discussion.html",
    "size": 490036,
    "sizeFormatted": "478.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Erythrocytes",
    "mtime": 1791413530.0433521
  },
  {
    "name": "L8_Hemolytic_S1_Mind_Map.html",
    "title": "Hemolytic",
    "path": "Lecture/Erythrocytes/L8_Hemolytic_S1_Mind_Map.html",
    "size": 148494,
    "sizeFormatted": "145.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Erythrocytes",
    "mtime": 1790713942.0
  },
  {
    "name": "L10_AML_S0_Discussion.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L10_AML_S0_Discussion.html",
    "size": 345243,
    "sizeFormatted": "337.2 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1791413529.3463137
  },
  {
    "name": "L10_AML_S1_Mind_Map.html",
    "title": "Acute Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L10_AML_S1_Mind_Map.html",
    "size": 123914,
    "sizeFormatted": "121.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790975645.651699
  },
  {
    "name": "L11_MPN_MDS_S0_Discussion.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L11_MPN_MDS_S0_Discussion.html",
    "size": 380848,
    "sizeFormatted": "371.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1791413529.4189482
  },
  {
    "name": "L11_MPN_MDS_S1_Mind_Map.html",
    "title": "Chronic Myeloid Neoplasms",
    "path": "Lecture/Leukocytes/L11_MPN_MDS_S1_Mind_Map.html",
    "size": 128491,
    "sizeFormatted": "125.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790975667.8418365
  },
  {
    "name": "L12_ALL_S0_Discussion.html",
    "title": "Lymphoid Neoplasms",
    "path": "Lecture/Leukocytes/L12_ALL_S0_Discussion.html",
    "size": 327642,
    "sizeFormatted": "320.0 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1791413529.467075
  },
  {
    "name": "L12_ALL_S1_Mind_Map.html",
    "title": "Lymphoid Neoplasms",
    "path": "Lecture/Leukocytes/L12_ALL_S1_Mind_Map.html",
    "size": 125132,
    "sizeFormatted": "122.2 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790975677.4982216
  },
  {
    "name": "L9_Benign_S0_Discussion.html",
    "title": "Benign Disorders",
    "path": "Lecture/Leukocytes/L9_Benign_S0_Discussion.html",
    "size": 377988,
    "sizeFormatted": "369.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Leukocytes",
    "mtime": 1791413529.2933445
  },
  {
    "name": "L9_Benign_S1_Mind_Map.html",
    "title": "Benign Disorders",
    "path": "Lecture/Leukocytes/L9_Benign_S1_Mind_Map.html",
    "size": 123943,
    "sizeFormatted": "121.0 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Leukocytes",
    "mtime": 1790975631.1665695
  },
  {
    "name": "L1_Hematopoiesis_S0_Discussion.html",
    "title": "Hematopoiesis",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S0_Discussion.html",
    "size": 400700,
    "sizeFormatted": "391.3 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1791413529.5291212
  },
  {
    "name": "L1_Hematopoiesis_S1_Blood_Composition.pdf",
    "title": "Blood Composition",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S1_Blood_Composition.pdf",
    "size": 317849,
    "sizeFormatted": "310.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019666.0
  },
  {
    "name": "L1_Hematopoiesis_S2_Hematopoiesis_Sites.pdf",
    "title": "Hematopoiesis Sites",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S2_Hematopoiesis_Sites.pdf",
    "size": 1318259,
    "sizeFormatted": "1.3 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019744.0
  },
  {
    "name": "L1_Hematopoiesis_S3_Hematopoiesis_Process.pdf",
    "title": "Hematopoiesis Process",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S3_Hematopoiesis_Process.pdf",
    "size": 1111963,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786019852.0
  },
  {
    "name": "L1_Hematopoiesis_S4_Mind_Map.html",
    "title": "Hematopoiesis",
    "path": "Lecture/Physiology/L1_Hematopoiesis_S4_Mind_Map.html",
    "size": 114117,
    "sizeFormatted": "111.4 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790713940.0
  },
  {
    "name": "L2_BCE_RBC-HGB_S0_Discussion.html",
    "title": "Leukocytes &amp; Thrombocytes",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S0_Discussion.html",
    "size": 345733,
    "sizeFormatted": "337.6 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1791413529.591348
  },
  {
    "name": "L2_BCE_RBC-HGB_S1_Erythrocyte.pdf",
    "title": "Erythrocyte",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S1_Erythrocyte.pdf",
    "size": 1418003,
    "sizeFormatted": "1.4 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786114769.0
  },
  {
    "name": "L2_BCE_RBC-HGB_S2_Hemoglobin.pdf",
    "title": "Hemoglobin",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S2_Hemoglobin.pdf",
    "size": 840386,
    "sizeFormatted": "820.7 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786114815.0
  },
  {
    "name": "L2_BCE_RBC-HGB_S3_Mind_Map.html",
    "title": "Erythrocytes & Hemoglobin",
    "path": "Lecture/Physiology/L2_BCE_RBC-HGB_S3_Mind_Map.html",
    "size": 100084,
    "sizeFormatted": "97.7 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790713971.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S0_Discussion.html",
    "title": "Leukocytes &amp; Thrombocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S0_Discussion.html",
    "size": 362632,
    "sizeFormatted": "354.1 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1791413529.6404128
  },
  {
    "name": "L3_BCE_WBC-PLT_S1_Granulocytes.pdf",
    "title": "Granulocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S1_Granulocytes.pdf",
    "size": 534379,
    "sizeFormatted": "521.9 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538835.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S2_Lymphocytes.pdf",
    "title": "Lymphocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S2_Lymphocytes.pdf",
    "size": 458102,
    "sizeFormatted": "447.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538871.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S3_Monocytes-Platelets.pdf",
    "title": "Monocytes & Platelets",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S3_Monocytes-Platelets.pdf",
    "size": 351447,
    "sizeFormatted": "343.2 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786538884.0
  },
  {
    "name": "L3_BCE_WBC-PLT_S4_Mind_Map.html",
    "title": "Leukocytes & Thrombocytes",
    "path": "Lecture/Physiology/L3_BCE_WBC-PLT_S4_Mind_Map.html",
    "size": 94783,
    "sizeFormatted": "92.6 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790713940.0
  },
  {
    "name": "L4_RBC_Analysis_S0_Discussion.html",
    "title": "RBC Analysis",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S0_Discussion.html",
    "size": 294839,
    "sizeFormatted": "287.9 KB",
    "extension": "html",
    "type": "Discussion",
    "category": "Lecture / Physiology",
    "mtime": 1791413529.6743371
  },
  {
    "name": "L4_RBC_Analysis_S1_RBC_Indices.pdf",
    "title": "RBC Indices",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S1_RBC_Indices.pdf",
    "size": 683427,
    "sizeFormatted": "667.4 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539106.0
  },
  {
    "name": "L4_RBC_Analysis_S2_RBC_Poikilocytes.pdf",
    "title": "RBC Poikilocytes",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S2_RBC_Poikilocytes.pdf",
    "size": 1156067,
    "sizeFormatted": "1.1 MB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539118.0
  },
  {
    "name": "L4_RBC_Analysis_S3_RBC_Inclusions.pdf",
    "title": "RBC Inclusions",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S3_RBC_Inclusions.pdf",
    "size": 1048420,
    "sizeFormatted": "1023.8 KB",
    "extension": "pdf",
    "type": "Slide Deck",
    "category": "Lecture / Physiology",
    "mtime": 1786539130.0
  },
  {
    "name": "L4_RBC_Analysis_S4_Mind_Map.html",
    "title": "RBC Analysis",
    "path": "Lecture/Physiology/L4_RBC_Analysis_S4_Mind_Map.html",
    "size": 96801,
    "sizeFormatted": "94.5 KB",
    "extension": "html",
    "type": "Mind Map",
    "category": "Lecture / Physiology",
    "mtime": 1790713941.0
  },
  {
    "name": "L1_Hematopoiesis_S1_Blood_Composition_Video",
    "title": "Blood Composition",
    "path": "https://youtu.be/jG0gyuxHCss",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/jG0gyuxHCss",
    "mtime": 0
  },
  {
    "name": "L1_Hematopoiesis_S2_Hematopoiesis_Sites_Video",
    "title": "Hematopoiesis Sites",
    "path": "https://youtu.be/-tAUTqSBBV8",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/-tAUTqSBBV8",
    "mtime": 0
  },
  {
    "name": "L1_Hematopoiesis_S3_Hematopoiesis_Process_Video",
    "title": "Hematopoiesis Process",
    "path": "https://youtu.be/F6M8pZDxGdw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/F6M8pZDxGdw",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_Hemocytometer_Video",
    "title": "Hemocytometer",
    "path": "https://youtu.be/GEtNXeqoKlo",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/GEtNXeqoKlo",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Demo_Hemocytometer_Thrombo_TIC_Setup",
    "title": "Hemocytometer Thrombo-TIC Setup",
    "path": "https://youtu.be/QTzEcoxlkoI",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/QTzEcoxlkoI",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_2_Demo_Hemocytometer_Charging",
    "title": "Hemocytometer Charging",
    "path": "https://youtu.be/m-EP2Vj_CQo",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/m-EP2Vj_CQo",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_3_Demo_Hemocytometer_Read",
    "title": "Hemocytometer Read",
    "path": "https://youtu.be/IdD9H5buUrA",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/IdD9H5buUrA",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Tool_Week_2_Hemocytometer",
    "title": "Week 2 Hemocytometer",
    "path": "https://teach.brettmrice.com/#week-2",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://teach.brettmrice.com/#week-2",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_Hematocrit_Video",
    "title": "Hematocrit",
    "path": "https://youtu.be/lojI06C6A5Q",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/lojI06C6A5Q",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_1_Demo_Hematocrit_Setup",
    "title": "Hematocrit Setup",
    "path": "https://youtu.be/4W0XvRYXTJw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/4W0XvRYXTJw",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S2_2_Demo_Hematocrit_Centrifuge_Read",
    "title": "Hematocrit Centrifuge & Read",
    "path": "https://youtu.be/0_Id8VUFsQ4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/0_Id8VUFsQ4",
    "mtime": 0
  },
  {
    "name": "L1_Manual_Counts_S1_1_Trainer_Hematocrit_Reader",
    "title": "Hematocrit Reader",
    "path": "https://www.brettmrice.com/Hematocrit-Trainer/",
    "size": 0,
    "sizeFormatted": "Interactive Trainer",
    "extension": "url",
    "type": "Trainer",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://www.brettmrice.com/Hematocrit-Trainer/",
    "mtime": 0
  },
  {
    "name": "L2_BCE_RBC-HGB_S1_Erythrocyte_Video",
    "title": "Erythrocyte",
    "path": "https://youtu.be/LcgQgGLCt5I",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/LcgQgGLCt5I",
    "mtime": 0
  },
  {
    "name": "L2_BCE_RBC-HGB_S2_Hemoglobin_Video",
    "title": "Hemoglobin",
    "path": "https://youtu.be/Bn2MnwjD51w",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/Bn2MnwjD51w",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_PBS_Preparation_Video",
    "title": "PBS Preparation",
    "path": "https://youtu.be/Mn4t2B3R_UY",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/Mn4t2B3R_UY",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_1_Demo_Slide_Prep_Microcapillary_Tube",
    "title": "Slide Prep Microcapillary Tube",
    "path": "https://youtu.be/_J5hAGrS650",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/_J5hAGrS650",
    "mtime": 0
  },
  {
    "name": "L2_Slide_Preparation_S1_2_Demo_Slide_Prep_Applicator_Stick",
    "title": "Slide Prep Applicator Stick",
    "path": "https://youtu.be/cjWf9c6Uqdw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/cjWf9c6Uqdw",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S1_Granulocytes_Video",
    "title": "Granulocytes",
    "path": "https://youtu.be/h-lqd3K_byM",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/h-lqd3K_byM",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S2_Lymphocytes_Video",
    "title": "Lymphocytes",
    "path": "https://youtu.be/dQ7j6_6IZig",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/dQ7j6_6IZig",
    "mtime": 0
  },
  {
    "name": "L3_BCE_WBC-PLT_S3_Monocytes-Platelets_Video",
    "title": "Monocytes & Platelets",
    "path": "https://youtu.be/S5z8BRAl9f4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/S5z8BRAl9f4",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S1_PBS_Evaluation_Video",
    "title": "PBS Evaluation",
    "path": "https://youtu.be/_RkPRVrStLM",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/_RkPRVrStLM",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_PBS_Morphologies_Video",
    "title": "PBS Morphologies",
    "path": "https://youtu.be/8Q7muZftcao",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/8Q7muZftcao",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_1_Demo_CPS_Tutorial",
    "title": "CPS Tutorial",
    "path": "https://www.youtube.com/watch?v=0m0JuzliCN4",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Demonstration",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://www.youtube.com/watch?v=0m0JuzliCN4",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_1_Tool_Week_3_Slides",
    "title": "Week 3 Slides",
    "path": "https://teach.brettmrice.com/#week-3",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://teach.brettmrice.com/#week-3",
    "mtime": 0
  },
  {
    "name": "L3_Slide_Evaluation_S2_2_Tool_Blood_Cell_ID",
    "title": "Blood Cell ID",
    "path": "https://bloodcellid.com/",
    "size": 0,
    "sizeFormatted": "Web Tool",
    "extension": "url",
    "type": "Tool",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://bloodcellid.com/",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S1_RBC_Indices_Video",
    "title": "RBC Indices",
    "path": "https://youtu.be/12lDKTSlcg0",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/12lDKTSlcg0",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S2_RBC_Poikilocytes_Video",
    "title": "RBC Poikilocytes",
    "path": "https://youtu.be/3-FpS1rfeuA",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/3-FpS1rfeuA",
    "mtime": 0
  },
  {
    "name": "L4_RBC_Analysis_S3_RBC_Inclusions_Video",
    "title": "RBC Inclusions",
    "path": "https://youtu.be/6JfUtpf2mvc",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Lecture / Physiology",
    "youtubeUrl": "https://youtu.be/6JfUtpf2mvc",
    "mtime": 0
  },
  {
    "name": "L4_CBC_Analysis_S1_Principles_Video",
    "title": "Principles",
    "path": "https://youtu.be/UIS-zmZTZeU",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/UIS-zmZTZeU",
    "mtime": 0
  },
  {
    "name": "L4_CBC_Analysis_S2_Parameters_Video",
    "title": "Parameters",
    "path": "https://youtu.be/113lBFF1Iuw",
    "size": 0,
    "sizeFormatted": "YouTube",
    "extension": "youtube",
    "type": "Video",
    "category": "Laboratory / CBC_PBS",
    "youtubeUrl": "https://youtu.be/113lBFF1Iuw",
    "mtime": 0
  }
];
